version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: Danylo73.
      DATABASE_NAME: db_tg_bot_watchlist
      REDIS_HOST: redis
      REDIS_PORT: 6379
      TMDB_API_KEY: 7a5283b6e82098bd6b75336b6a8eae96
      BOT_TOKEN: 7763262402:AAES8C69H70oiEXbQI6-Xpg4H8tVyTqPQV0
    depends_on:
      - db
      - redis
    volumes:
      - ./:/usr/src/app
    command: npm run start:dev

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Danylo73.
      POSTGRES_DB: db_tg_bot_watchlist
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - '6379:6379'

volumes:
  pgdata:
